// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVAkFzad3SQZxli61eQAy-r-_NWLHA1h4',
    appId: '1:608884032700:web:8ffac263cf9c41c7d57cb9',
    messagingSenderId: '608884032700',
    projectId: 'flutterbasicinsta',
    authDomain: 'flutterbasicinsta.firebaseapp.com',
    storageBucket: 'flutterbasicinsta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnUs560ziZ72VrPrUjPdLZvuZdYBXLxBg',
    appId: '1:608884032700:android:77d22d830aeefe06d57cb9',
    messagingSenderId: '608884032700',
    projectId: 'flutterbasicinsta',
    storageBucket: 'flutterbasicinsta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGI1sF1b4cwy9IEi0guRmoNRFealhWlAc',
    appId: '1:608884032700:ios:36da9399eda6bd2cd57cb9',
    messagingSenderId: '608884032700',
    projectId: 'flutterbasicinsta',
    storageBucket: 'flutterbasicinsta.firebasestorage.app',
    iosBundleId: 'com.kenant42.instagramclone.instagramcloneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGI1sF1b4cwy9IEi0guRmoNRFealhWlAc',
    appId: '1:608884032700:ios:36da9399eda6bd2cd57cb9',
    messagingSenderId: '608884032700',
    projectId: 'flutterbasicinsta',
    storageBucket: 'flutterbasicinsta.firebasestorage.app',
    iosBundleId: 'com.kenant42.instagramclone.instagramcloneapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVAkFzad3SQZxli61eQAy-r-_NWLHA1h4',
    appId: '1:608884032700:web:bfef6f7dc6bdef74d57cb9',
    messagingSenderId: '608884032700',
    projectId: 'flutterbasicinsta',
    authDomain: 'flutterbasicinsta.firebaseapp.com',
    storageBucket: 'flutterbasicinsta.firebasestorage.app',
  );

}